#+TITLE: Notes

* DONE Things to test
CLOSED: [2019-04-27 Sat 16:25]
- Test using text-short and intern for certain strings
* CANCELLED Shards need some way of making requests (get gateway, etc)
CLOSED: [2019-02-24 Sun 18:29]
- [X] Instead we just pass the gateway url to shards, it never changes, so w/e

* TODO Function to log out the bot, waiting for all stuff to end, etc
- we'll need some control messages that tell the client to enter a loop of
  waiting for all shards to signal that they are closed.

** Shard shutdown process?
- Send shutdown signal to shard
- Shard shuts down and sends a control message with it's own thread to the client stating that it is closed?
- Client removes shard from the set of shards

* DONE Move from lists of objects to maps of id => object
CLOSED: [2019-03-05 Tue 02:44]
* DONE Partial data
CLOSED: [2019-03-29 Fri 13:38]

* DONE Presence info
CLOSED: [2019-04-27 Sat 16:25]
- linky :: https://discordapp.com/developers/docs/topics/gateway#presence-update
* DONE Allow options for presences to be discarded
CLOSED: [2019-05-26 Sun 05:33]
- Pretty much nobody cares about presences on a bot but presences take up *a
  lot* of data (Turns out they don't lol)
* DONE Share user data
CLOSED: [2019-05-27 Mon 02:58]
instead of having a copy for each user object discord gives us.
This is probably a much better optimisation that discarding presences.
* TODO Migrate from Transformers and MTL to Free monads
should be fun
* TODO Use barbies for data that updates (w/ magic defaulting stuff for aeson idk?)
