name:               calamity-commands
version:            0.1.3.0
github:             "simmsb/calamity"
homepage:           https://github.com/simmsb/calamity
bug-reports:        https://github.com/simmsb/calamity/issues
license:            MIT
license-file:       LICENSE
author:             "Ben Simms"
maintainer:         "ben@bensimms.moe"
copyright:          2020 Ben Simms
category:           Utils
tested-with:        GHC == 8.10.4

extra-source-files:
  - README.md
  - ChangeLog.md

extra-doc-files:
  - README.md

synopsis:           "A library for declaring, parsing, and invoking text-input based commands"
# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        Please see the README on GitHub at <https://github.com/simmsb/calamity#readme>

dependencies:
- base >= 4.13 && < 5
- lens >= 4.18 && < 6
- generic-lens >= 2.0 && < 3
- text >= 1.2 && < 2.1
- unordered-containers >= 0.2 && < 0.3
- polysemy >= 1.5 && < 2
- polysemy-plugin >= 0.3 && < 0.5
- text-show >= 3.8 && < 4
- megaparsec >= 8 && < 10

library:
  ghc-options:
    - -fplugin=Polysemy.Plugin
    - -funbox-strict-fields
    - -Wall
    - -fno-warn-name-shadowing
  source-dirs: .

default-extensions:
  - StrictData
  - AllowAmbiguousTypes
  - BlockArguments
  - NoMonomorphismRestriction
  - BangPatterns
  - BinaryLiterals
  - UndecidableInstances
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - DerivingVia
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  - DeriveAnyClass
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - OverloadedLabels
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
  - DuplicateRecordFields
  - TypeOperators
  - TypeApplications
  - RoleAnnotations
